### ISSUE TITLE
Specify browser URL option

### ISSUE THREAD

**Issue by AlecRust** [fogleman/FeedNotifier#15]
It would be great if you could add a field in the options to allow the user to specify a path to the browser they'd like to open links in.

For instance, I use Chrome Canary as my main browser which I'm unable to set as my system "default browser". Specifying a path would get around this and a few other edge-case issues. It's quite a common option to have these days.

**Comment by raymondlaw** [comment]
I was able to get Chrome Canary on Windows 7 working by fiddling with the Default Programs changing almost everything from IE to Chrome.
