### ISSUE TITLE
several feeds report that url does not appear to be a valid rss/atom feed

### ISSUE THREAD

**Issue by mispp** [fogleman/FeedNotifier#51]
http://www.monitor.hr/rss/
http://www.phoronix.com/rss.php

**Comment by Xyl2k** [comment]
same issue here, appear to be in view.py, message defined here https://github.com/fogleman/FeedNotifier/blob/master/view.py#L169
proc here: https://github.com/fogleman/FeedNotifier/blob/master/view.py#L202
definition in util.py: https://github.com/fogleman/FeedNotifier/blob/master/util.py#L86

**Comment by developer0725** [comment]
I have done.
Some of feed engines don't accept custom user-agent.
change user-agent to browser's user-agent(chrome or firefox).
