### ISSUE TITLE
How to build the exe from source?

### ISSUE THREAD

**Issue by onlinesid** [fogleman/FeedNotifier#81]
Please help. Is there an information about how I can download this source code and build the exe installer myself? I'm guessing something about python on Windows? That or using VS community edition?

**Comment by fogleman** [comment]
setup.py, which uses py2exe, is what creates the exe file.

**Comment by onlinesid** [comment]
Thank you for the quick reply and for the info. Not a Python person myself hence my unfamiliarity with Python world, but this project might turn me into one
