### ISSUE TITLE
How to set the default duration and polling interval?

### ISSUE THREAD

**Issue by onlinesid** [fogleman/FeedNotifier#85]
I'm trying to set these two defaults for installation:

Set popup duration to infinite
Set polling interval to 2 minutes

For popup duration, I tried POPUP_DURATION to 0 or -1 but that does not work. 

I tried setting DEFAULT_POLLING_INTERVAL = 60 * 2 but it always defaulted to 1 day.

Please help

**Comment by onlinesid** [comment]
Actually I can see errors in the log:

WARNING: yacc table file version is out of date
WARNING: Couldn't open 'parser.out'. [Errno 2] No such file or directory: 'C:\\Program Files (x86)\\Feed Notifier\\library.zip\\parser.out'
Generating LALR tables
WARNING: Couldn't create 'parsetab'. [Errno 2] No such file or directory: 'C:\\Program Files (x86)\\Feed Notifier\\library.zip\\parsetab.py'
C:\Program Files (x86)\Feed Notifier\notifier.exe:39: wxPyDeprecationWarning: Using deprecated class PySimpleApp. 

What does that mean?

**Comment by fogleman** [comment]
`POPUP_AUTO_PLAY = False` for infinite duration.

Feed Notifier tries to guess a good interval based on the RSS feed:

https://github.com/fogleman/FeedNotifier/blob/786111338790e0031c58b4286a361af3452442b8/util.py#L141

**Comment by onlinesid** [comment]
I've figured it out now, thanks :+1:
