### ISSUE TITLE
How to change installation folder name?

### ISSUE THREAD

**Issue by onlinesid** [fogleman/FeedNotifier#86]
No matter what I changed in setup.py it seems to always default the installation folder to "C:\Program Files (x86)\Feed Notifier".

How can I default it to a different folder name like 'My Feed Notifier' for example?

Many thanks.

**Comment by fogleman** [comment]
https://github.com/fogleman/FeedNotifier/blob/master/installer.iss#L15

**Comment by onlinesid** [comment]
Thank you, that does it! :+1:
