### ISSUE TITLE
Publicate RSS feeds for Twitter feed/lists rejected as invalid 

### ISSUE THREAD

**Issue by velw** [fogleman/FeedNotifier#92]
When I use the free http://publicate.it service to create an RSS feed for a Twitter list, and try to add the URL as a new feed in Feed Notifier, I get the following error message:

>  The URL entered does not appear to be a valid RSS/Atom feed.

The RSS data is loaded successfully in other RSS clients.

Please could someone take a look and see what's going on here?

**Comment by developer0725** [comment]
I have done.
Some of feed engines don't accept custom user-agent.
change user-agent to browser's user-agent(chrome or firefox).

**Comment by velw** [comment]
I can't test this any more but it sounds like this issue is closed (thank you developer0725), so I will close it.
